Repository UnicusDevs/COVID19NeighbourhoodAwareness, pull requests merged in 2020-04, with the labels that each got.

#22 Feature/max kelly/post backend
  controllers/authentication_controller.js
  controllers/post_controller.js
  controllers/user_controller.js
  models/Post.js
  routes/api/login.js
  routes/api/post.js
  routes/api/signUp.js
  routes/api/user.js
  server.js
Labels: enhancement

#24 Feature/max kelly/log status
  client/src/components/LogStatus.js
  client/src/sass/components/LogStatus.module.scss
Labels: enhancement

#30 Feature/max kelly/signup module
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/api/baseURL.js
  client/src/components/Header.js
  client/src/components/LogInForm.js
  client/src/components/LogStatus.js
  client/src/components/LogStatusButton.js
  client/src/components/LoginModule.js
  client/src/components/SignUpForm.js
  client/src/components/SignUpModule.js
  client/src/index.js
  client/src/logo.svg
  client/src/pages/LandingPage.js
  client/src/pages/LoginPage.js
  client/src/pages/SignUpPage.js
  client/src/redux/actions/allActions.js
  client/src/redux/actions/popUpActions.js
  client/src/redux/actions/signupFormActions.js
  client/src/redux/actions/toDeleteFile.js
  client/src/redux/configureStore.js
  client/src/redux/reducers/popUpReducer.js
  client/src/redux/reducers/rootReducer.js
  client/src/redux/reducers/signUpFormReducer.js
  client/src/redux/reducers/toDeleteFile.js
  client/src/redux/store.js
  client/src/routes/AppRouter.js
  client/src/sass/components/Header.module.scss
  client/src/sass/components/SignupForm.module.scss
  controllers/authentication_controller.js
  controllers/user_controller.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#31 Feature/max kelly/home page
  client/package-lock.json
  client/package.json
  client/src/api/getUserData.js
  client/src/components/About.js
  client/src/components/Header.js
  client/src/components/LogInForm.js
  client/src/components/LogStatusButton.js
  client/src/pages/homePage.js
  client/src/redux/actions/allActions.js
  client/src/redux/actions/signupFormActions.js
  client/src/redux/actions/userActions.js
  client/src/redux/configureStore.js
  client/src/redux/reducers/rootReducer.js
  client/src/redux/reducers/userReducer.js
  client/src/routes/AppRouter.js
  client/src/sass/components/Header.module.scss
  controllers/authentication_controller.js
  controllers/user_controller.js
  package-lock.json
  package.json
  routes/api/home.js
  routes/api/login.js
  routes/api/signUp.js
  routes/api/user.js
  server.js
  validation.js
Labels: enhancement

#34 Feature/max kelly/handle post
  client/package-lock.json
  client/package.json
  client/src/api/handlePost.js
  client/src/components/Feed.js
  client/src/components/Header.js
  client/src/components/LogInForm.js
  client/src/components/LogStatus.js
  client/src/components/LogStatusButton.js
  client/src/components/SignUpForm.js
  client/src/pages/SignUpPage.js
  client/src/pages/homePage.js
  client/src/redux/actions/allActions.js
  client/src/redux/actions/postActions.js
  client/src/redux/reducers/postReducer.js
  client/src/redux/reducers/rootReducer.js
  client/src/redux/reducers/signUpFormReducer.js
  controllers/authentication_controller.js
  controllers/post_controller.js
  controllers/user_controller.js
  routes/api/home.js
  routes/api/post.js
  routes/api/user.js
Labels: enhancement

#41 sorted the posts by date
  controllers/post_controller.js
Labels: enhancement

#46 Feature/max kelly/handle claps
  client/src/components/Feed.js
  client/src/components/LogStatus.js
  client/src/components/LoginForm.js
  client/src/sass/components/LogStatus.module.scss
  controllers/post_controller.js
  routes/api/post.js
Labels: enhancement

#49 Feature/max kelly/limit log status to one day
  client/src/api/getUserData.js
  client/src/api/handlePost.js
  client/src/components/Feed.js
  client/src/components/Header.js
  client/src/components/LogStatus.js
  client/src/components/LogStatusButton.js
  client/src/components/SignUpForm.js
  client/src/index.js
  client/src/redux/actions/allActions.js
  client/src/redux/actions/postActions.js
  client/src/redux/reducers/postReducer.js
  client/src/sass/components/LogStatusButton.module.scss
  controllers/post_controller.js
  controllers/user_controller.js
  routes/api/post.js
Labels: enhancement

#51 Feature/max kelly/infinity scroll
  .vscode/settings.json
  client/src/api/handlePost.js
  client/src/components/About.js
  client/src/components/Feed.js
  client/src/components/Header.js
  client/src/pages/HomePage.js
  client/src/pages/LoginPage.js
  client/src/routes/AppRouter.js
  client/src/sass/components/About.module.scss
  client/src/sass/components/Feed.module.scss
  client/src/sass/components/Header.module.scss
  client/src/sass/main.scss
  client/src/sass/pages/HomePage.module.scss
  client/src/sass/pages/LandingPage.module.scss
  controllers/post_controller.js
  controllers/user_controller.js
  package-lock.json
  package.json
  routes/api/post.js
Labels: enhancement

#54 Feature/tomlinson/sign up page
  client/src/components/About.js
  client/src/components/BackButton.js
  client/src/components/Header.js
  client/src/components/LoginForm.js
  client/src/components/SecondaryHeader.js
  client/src/components/SignUpForm.js
  client/src/components/SignUpModule.js
  client/src/pages/HomePage.js
  client/src/pages/LoginPage.js
  client/src/pages/SignUpPage.js
  client/src/routes/AppRouter.js
  client/src/sass/components/About.module.scss
  client/src/sass/components/BackButton.module.scss
  client/src/sass/components/Header.module.scss
  client/src/sass/components/LogStatusButton.module.scss
  client/src/sass/components/LoginForm.module.scss
  client/src/sass/components/SecondaryHeader.module.scss
  client/src/sass/components/SignUpModal.module.scss
  client/src/sass/components/SignupForm.module.scss
  client/src/sass/main.scss
  client/src/sass/pages/LoginPage.module.scss
  client/src/sass/pages/SignupPage.module.scss
Labels: enhancement

#53 Feature/max kelly/google suburb api
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/api/googleAPI/handleGoogleAPI.js
  client/src/components/SignUpForm.js
  client/src/redux/actions/signupFormActions.js
  client/src/redux/reducers/signUpFormReducer.js
  client/src/sass/components/SignupForm.module.scss
Labels: enhancement

#58 Feature/max kelly/filter by user suburb
  client/package-lock.json
  client/src/api/handlePost.js
  client/src/components/Feed.js
  client/src/components/Header.js
  client/src/components/LogStatusButton.js
  client/src/redux/actions/allActions.js
  client/src/redux/actions/postActions.js
  client/src/redux/reducers/postReducer.js
  client/src/routes/AppRouter.js
  client/src/sass/components/Feed.module.scss
  controllers/post_controller.js
  package-lock.json
  routes/api/post.js
Labels: enhancement

#59 Feature/max kelly/add profile image to sign up
  client/src/api/registration.js
  client/src/assets/icons8-login-as-user-96.png
  client/src/assets/icons8-name-96.png
  client/src/components/LogStatus.js
  client/src/components/SignUpForm.js
  client/src/redux/reducers/signUpFormReducer.js
  client/src/sass/components/SignupForm.module.scss
  controllers/user_controller.js
  uploads/2020-04-20T07:44:29.766ZOval.png
Labels: enhancement

#60 change name of app to NeighboursBook
  README.md
  client/src/components/About.js
  client/src/components/Header.js
  client/src/components/LogStatusButton.js
  client/src/sass/components/LogStatus.module.scss
Labels: bug, wording

#66 added default image to signup image selection
  client/src/components/SignUpForm.js
  client/src/sass/components/SignupForm.module.scss
Labels: enhancement

#65 fixed scroll issue on mobile view
  client/src/sass/main.scss
Labels: bug

#63 fixed filter by suburb
  client/src/api/googleAPI/handleGoogleAPI.js
  client/src/api/handlePost.js
  client/src/components/Feed.js
  client/src/components/Header.js
  controllers/post_controller.js
Labels: bug

#86 testing what breaks heroku
  client/package.json
  client/src/api/baseURL.js
  controllers/user_controller.js
  server.js
  uploads/2020-04-23T01:19:02.767ZT1UKY47JR-U1UKN0QJG-155c4fb71458-72.png
Labels: enhancement

#84 changed name
  client/src/components/Header.js
Labels: bug

#85 if user goes to no page found then they're redirected back to the homepage
  client/src/routes/AppRouter.js
Labels: enhancement

#88 complete the seperation from live to local
  client/src/api/baseURL.js
  server.js
Labels: enhancement

#98 Feature/max kelly/change image storage tos3
  client/public/.well-known/acme-challenge/Jq1J2ISAHf4YLfZFeMp7GsQgY_p1v-OHY09Qh-BWg8I-1
  client/public/.well-known/acme-challenge/yjbd4HNZ50Y4mh7i2Mqb6GjaR6R4COfRYflzTz-cY4s
  client/src/api/registration.js
  client/src/components/Header.js
  client/src/components/SignUpForm.js
  controllers/fileUpload_controller.js
  controllers/user_controller.js
  package-lock.json
  package.json
  routes/api/signUp.js
  server.js
Labels: bug, enhancement

#101 staging to master
  client/public/.well-known/acme-challenge/Jq1J2ISAHf4YLfZFeMp7GsQgY_p1v-OHY09Qh-BWg8I-1
  client/public/.well-known/acme-challenge/yjbd4HNZ50Y4mh7i2Mqb6GjaR6R4COfRYflzTz-cY4s
  client/public/index.html
  client/src/api/registration.js
  client/src/components/Feed.js
  client/src/components/Header.js
  client/src/components/LogStatus.js
  client/src/components/SignUpForm.js
  client/src/sass/components/LogStatus.module.scss
  controllers/fileUpload_controller.js
  controllers/user_controller.js
  package-lock.json
  package.json
  routes/api/signUp.js
  server.js
Labels: bug, enhancement, wording

#103 Hotfix/max kelly/changed limit on post request so paginated posts works
  client/src/api/handlePost.js
  controllers/post_controller.js
Labels: bug

#104 Hotfix
  client/src/api/handlePost.js
  controllers/post_controller.js
Labels: bug

#105 to prevent the user from double clicking and submitting two statuses …
  client/src/components/LogStatusButton.js
Labels: bug

#106 added page refresh once user logs
  client/src/components/LogStatusButton.js
Labels: bug
